apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust-deployment
spec:
  replicas: 1  # Mínimo para HPA
  selector:
    matchLabels:
      app: api-rust
  template:
    metadata:
      labels:
        app: api-rust
    spec:
      containers:
        - name: api-rust
          image: 34.69.137.65.nip.io/proyecto/api_rust:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "75m"
              memory: "96Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-rust-service
spec:
  type: ClusterIP
  selector:
    app: api-rust
  ports:
    - port: 8080
      targetPort: 8080