apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-deployment
  namespace: ingress-nginx
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc-server
          image: 34.69.137.65.nip.io/proyecto/api_go_grpc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: RABBITMQ_ADDR
              value: amqp://guest:guest@rabbitmq:5672/
            - name: KAFKA_ADDR
              value: kafka:9092
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "75m"
              memory: "96Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
  namespace: ingress-nginx
spec:
  type: ClusterIP
  selector:
    app: grpc
  ports:
    - port: 50051
      targetPort: 50051
