apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: 34.69.137.65.nip.io
      http:
        paths:
          - path: /input(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-rust-service
                port:
                  number: 8080
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
