apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: harbor.HARBOR_PLACEHOLDER.nip.io/proyecto/rabbitmq_consumer:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_ADDR
              value: amqp://guest:guest@rabbitmq:5672/
            - name: VALKEY_ADDR
              value: valkey:6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "200Mi"
              cpu: "250m"
