apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: 34.69.137.65.nip.io/proyecto/rabbitmq_consumer:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_ADDR
              value: amqp://guest:guest@rabbitmq-svc:5672/
            - name: VALKEY_ADDR
              value: valkey:6379
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "75m"
              memory: "96Mi"
